"""Provider service: CRUD on providers."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import Provider
from app.db.uuid import uuid_equals
from app.schemas.api import ProviderCreate, ProviderPatch


async def list_providers(session: AsyncSession, include_deleted: bool = False) -> list[Provider]:
    """List all providers, optionally including soft-deleted ones."""
    query = select(Provider).order_by(Provider.name)
    if not include_deleted:
        query = query.where(Provider.deleted_at.is_(None))
    res = await session.execute(query)
    return list(res.scalars().all())


async def get_provider(
    session: AsyncSession, provider_id: uuid.UUID, include_deleted: bool = False
) -> Provider | None:
    """Get a provider by UUID, optionally including soft-deleted ones."""
    query = select(Provider).where(uuid_equals(Provider.uuid_id, provider_id))
    if not include_deleted:
        query = query.where(Provider.deleted_at.is_(None))
    res = await session.execute(query)
    return res.scalar_one_or_none()


async def find_provider_by_uuid(
    session: AsyncSession, provider_uuid: uuid.UUID, include_deleted: bool = True
) -> Provider | None:
    """Resolve a provider by its UUID snapshot.

    Use this when cross-referencing a `probe_results.provider_uuid_at_probe`
    back to the current `providers` row. Defaults to `include_deleted=True`
    so historical probes of soft-deleted providers can still be
    attributed.

    Returns `None` if the provider was hard-deleted and no longer exists
    in the table (the snapshot is the only remaining evidence).
    """
    return await get_provider(session, provider_uuid, include_deleted=include_deleted)


async def create_provider(session: AsyncSession, data: ProviderCreate) -> Provider:
    """Create a new provider.

    `uuid_id` is auto-generated by the DB default unless `data.uuid_id`
    is supplied. The import path uses this to round-trip the same UUID
    the export had, so downstream cross-references (favorites with
    provider_uuid, probe_results.provider_uuid_at_probe) stay valid
    across export/import cycles.
    """
    p = Provider(
        uuid_id=data.uuid_id if data.uuid_id is not None else uuid.uuid4(),
        name=data.name,
        kind=data.kind,
        base_url=data.base_url,
        api_key=data.api_key,
        proxy=data.proxy,
        enabled=data.enabled,
        interval_seconds=data.interval_seconds,
        timeout_seconds=data.timeout_seconds,
        headers_json=data.headers_json,
    )
    session.add(p)
    await session.commit()
    await session.refresh(p)
    return p


async def patch_provider(
    session: AsyncSession, provider_id: uuid.UUID, data: ProviderPatch
) -> Provider | None:
    """Update a provider by UUID (only active providers)."""
    p = await get_provider(session, provider_id, include_deleted=False)
    if p is None:
        return None
    for field_, value in data.model_dump(exclude_unset=True).items():
        setattr(p, field_, value)
    await session.commit()
    await session.refresh(p)
    return p


async def delete_provider(session: AsyncSession, provider_id: uuid.UUID) -> bool:
    """Soft-delete a provider by setting deleted_at timestamp."""
    p = await get_provider(session, provider_id, include_deleted=False)
    if p is None:
        return False
    p.deleted_at = datetime.now(UTC)
    await session.commit()
    return True
