"""add_uuid_snapshot_softdelete_fields

Revision ID: 0158e57e3489
Revises: 4a7be4f2d8b0
Create Date: 2026-06-04 20:24:27.118797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0158e57e3489"
down_revision: Union[str, Sequence[str], None] = "4a7be4f2d8b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: We intentionally skip apscheduler_jobs table operations
    # as it's managed by APScheduler, not our ORM models.

    # Add UUID columns (nullable initially, will populate then make NOT NULL)
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("probe_results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid_id", sa.Uuid(), nullable=True))
        # Snapshot fields - nullable for existing data, will be required for new records
        batch_op.add_column(sa.Column("provider_name_at_probe", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("model_id_at_probe", sa.String(length=300), nullable=True))

    # Populate UUID columns for existing data
    # Using Python's uuid4 to generate unique UUIDs
    import uuid
    from sqlalchemy import text

    # Get connection for executing updates
    conn = op.get_bind()

    # Populate providers.uuid_id
    providers = conn.execute(text("SELECT id FROM providers")).fetchall()
    for row in providers:
        provider_id = row[0]
        new_uuid = str(uuid.uuid4())
        conn.execute(
            text("UPDATE providers SET uuid_id = :uuid WHERE id = :id"), {"uuid": new_uuid, "id": provider_id}
        )

    # Populate models.uuid_id
    models = conn.execute(text("SELECT id FROM models")).fetchall()
    for row in models:
        model_id = row[0]
        new_uuid = str(uuid.uuid4())
        conn.execute(
            text("UPDATE models SET uuid_id = :uuid WHERE id = :id"), {"uuid": new_uuid, "id": model_id}
        )

    # Populate probe_results.uuid_id and snapshot fields
    probe_results = conn.execute(text("SELECT id, provider_id, model_id FROM probe_results")).fetchall()
    for row in probe_results:
        result_id = row[0]
        provider_id = row[1]
        model_id = row[2]
        new_uuid = str(uuid.uuid4())

        # Get provider name and model_id string for snapshot
        provider_name = None
        model_id_str = None
        if provider_id:
            provider = conn.execute(
                text("SELECT name FROM providers WHERE id = :id"), {"id": provider_id}
            ).fetchone()
            if provider:
                provider_name = provider[0]
        if model_id:
            model = conn.execute(
                text("SELECT model_id FROM models WHERE id = :id"), {"id": model_id}
            ).fetchone()
            if model:
                model_id_str = model[0]

        conn.execute(
            text("""UPDATE probe_results
                   SET uuid_id = :uuid,
                       provider_name_at_probe = :provider_name,
                       model_id_at_probe = :model_id_str
                   WHERE id = :id"""),
            {"uuid": new_uuid, "provider_name": provider_name, "model_id_str": model_id_str, "id": result_id},
        )

    # Now make uuid_id columns NOT NULL and add unique indexes
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.alter_column("uuid_id", nullable=False)
        batch_op.create_index(batch_op.f("ix_providers_uuid_id"), ["uuid_id"], unique=True)

    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.alter_column("uuid_id", nullable=False)
        batch_op.create_index(batch_op.f("ix_models_uuid_id"), ["uuid_id"], unique=True)

    with op.batch_alter_table("probe_results", schema=None) as batch_op:
        batch_op.alter_column("uuid_id", nullable=False)
        # provider_name_at_probe should be NOT NULL for new records
        # but we keep it nullable for historical data that might not have it
        batch_op.create_index(batch_op.f("ix_probe_results_uuid_id"), ["uuid_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: We intentionally skip apscheduler_jobs table operations

    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_providers_uuid_id"))
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("uuid_id")

    with op.batch_alter_table("probe_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_probe_results_uuid_id"))
        batch_op.drop_column("model_id_at_probe")
        batch_op.drop_column("provider_name_at_probe")
        batch_op.drop_column("uuid_id")

    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_models_uuid_id"))
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("uuid_id")

    # ### end Alembic commands ###
